name: Inject Google Analytics Tag

on:
  push:
    branches:
      - gh-pages  # Adjust this to match your deployment branch

jobs:
  inject-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject GA4 Script into HTML files
        env:
          GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
        run: |
          # Define the GA4 snippet using your GitHub Secret
          GA_SCRIPT='<!-- Google tag (gtag.js) --><script async src="https://www.googletagmanager.com/gtag/js?id=G-9S8H0YV4GD"></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config',"'$GA_MEASUREMENT_ID'");</script>
          
          # Find all HTML files and insert the snippet right before </head>
          find . -name "cv.html" -type f | while read file; do
            sed -i "s|<\/head>|${GA_SCRIPT}<body>|g" "$file"
          done
